language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt

script:
  - export BASE=`pwd`
  - source test/setup.sh
  - coverage run setup.py test

notifications:
  email:
    receipients:
      - anastassios.martakos@gmail.com
    on_success: always
    on_failure: always

  after_success:
    - coveralls
